educateur_homepage:
    path:     /
    defaults: { _controller: EducateurBundle:Default:index }

educateur_enfant_ajout:
    path:     /ajout-enfant
    defaults: { _controller: EducateurBundle:Default:ajoutEnfant }

educateur_creer_sequence:
    path:     /creer-sequence
    defaults: { _controller: EducateurBundle:Default:creerSequence }

educateur_fiche_enfant:
    path:     /{username}-{name}
    defaults: { _controller: EducateurBundle:Default:ficheEnfant }

educateur_creer_contrat:
    path:     /{username}-{name}/creer-contrat
    defaults: { _controller: EducateurBundle:Default:creerContrat }

educateur_enfant_modif:
    path:     /{username}-{name}/modif-enfant
    defaults: { _controller: EducateurBundle:Default:modifEnfant }
