educateur_homepage:
    path:     /
    defaults: { _controller: EducateurBundle:Default:index }

educateur_enfant_ajout:
    path:     /ajout-enfant
    defaults: { _controller: EducateurBundle:Default:ajoutEnfant }

educateur_creer_sequence:
    path:     /creer-sequence
    defaults: { _controller: EducateurBundle:Default:creerSequence }